### ISSUE TITLE
Secure key in 2 part ?

### ISSUE THREAD

**Issue by xorgxx** [GiveMeAllYourCats/DoctrineEncryptBundle#46]
Hi for security reasons (not have only one key to access data). If I understand well now, the system can be corrupt if you can have access to this key. If we have to in different localisation it will increase secure data,
it's possible to share the key and put into different server localisation. maybe access by restApi

```
// Config.yml
ambta_doctrine_encrypt:
    secret_directory_path-1:   # Default value
    secret_directory_path-2:   # Default value
```
maybe not possible ?

Thank
